services:
  - type: web
    name: nse-insight
    runtime: python
    plan: free

    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput

    startCommand: >
      waitress-serve
      --listen=0.0.0.0:$PORT
      --threads=1
      nse_insight.wsgi:application

    healthCheckPath: /health/

    autoDeploy: true

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "0"

      - key: PYTHON_VERSION
        value: "3.13.15"

      - key: OMP_NUM_THREADS
        value: "1"

      - key: OPENBLAS_NUM_THREADS
        value: "1"

      - key: MKL_NUM_THREADS
        value: "1"

      - key: NUMEXPR_NUM_THREADS
        value: "1"
